FROM metasploitframework/metasploit-framework

USER root

# Installer Python3 et pip
RUN apk add --no-cache python3 py3-pip || \
    yum install -y python3 python3-pip || \
    echo "ERROR: Impossible d'installer Python automatiquement"
# Définir le dossier de travail
WORKDIR /app

# Copier ton script Python dans l'image
COPY msf_auto_scan.py .

# Définir la commande par défaut à l'exécution du conteneur
CMD ["python3", "/app/msf_auto_scan.py"]
