FROM metasploitframework/metasploit-framework

USER root

RUN apt-get update && apt-get install -y python3 python3-pip && apt-get clean

WORKDIR /app

# Copier uniquement les fichiers nécessaires (adaptable)
COPY msf_auto_scan.py /app/msf_auto_scan.py
COPY metasploit/ /app/metasploit/

# Installer les dépendances Python si besoin (ajoute ici tes pip install)
# RUN pip3 install -r requirements.txt

USER msf

CMD ["python3", "/app/msf_auto_scan.py"]
